package Code;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        //set logo
//        ImageIcon icon4 = new javax.swing.ImageIcon(getClass().getResource("/icons/Untitled.jpg"));
//        Image scaledImage4 = icon4.getImage().getScaledInstance(260, 130, Image.SCALE_SMOOTH);
//        lbl_username1.setIcon(new ImageIcon(scaledImage4));
            
        // Set the desired width and height for the image
        int width = 100; // Set your desired width
        int height = 130; // Set your desired height

        // Create a new ImageIcon with the specified dimensions
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/icons/s.jpg"));
        Image scaledImage = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        lbl_std.setIcon(new ImageIcon(scaledImage));

        lbl_std.setText("  Students");
        
        ImageIcon icon2 = new javax.swing.ImageIcon(getClass().getResource("/icons/faculty.jpeg"));
        Image scaledImage2 = icon2.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        lbl_teacher.setIcon(new ImageIcon(scaledImage2));

        lbl_teacher.setText("  Teachers");
        
        ImageIcon icon3 = new javax.swing.ImageIcon(getClass().getResource("/icons/score.jpeg"));
        Image scaledImage3 = icon3.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        lbl_score.setIcon(new ImageIcon(scaledImage3));

        lbl_score.setText("  View Score");
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        panel_logout = new javax.swing.JPanel();
        lbl_logout = new javax.swing.JLabel();
        lbl_username1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panel_std = new javax.swing.JPanel();
        lbl_std = new javax.swing.JLabel();
        panel_mark = new javax.swing.JPanel();
        lbl_marksheet = new javax.swing.JLabel();
        panel_course = new javax.swing.JPanel();
        lbl_course = new javax.swing.JLabel();
        panel_teacher = new javax.swing.JPanel();
        lbl_teacher = new javax.swing.JLabel();
        panel_fees = new javax.swing.JPanel();
        lbl_fee = new javax.swing.JLabel();
        panel_score = new javax.swing.JPanel();
        lbl_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Welcome");

        panel_logout.setBackground(new java.awt.Color(0, 102, 102));

        lbl_logout.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        lbl_logout.setText("   Logout");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_logoutLayout = new javax.swing.GroupLayout(panel_logout);
        panel_logout.setLayout(panel_logoutLayout);
        panel_logoutLayout.setHorizontalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
            .addGroup(panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_logoutLayout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(lbl_logout)
                    .addGap(0, 31, Short.MAX_VALUE)))
        );
        panel_logoutLayout.setVerticalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_logoutLayout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(lbl_logout)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        lbl_username1.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        lbl_username1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Untitled.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199)
                .addComponent(lbl_username1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 180));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        panel_std.setBackground(new java.awt.Color(0, 102, 102));

        lbl_std.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_std.setForeground(new java.awt.Color(255, 255, 255));
        lbl_std.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/text-book-opened-from-top-view.png"))); // NOI18N
        lbl_std.setText("   Courses");
        lbl_std.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_stdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_stdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_stdMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_stdMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_stdLayout = new javax.swing.GroupLayout(panel_std);
        panel_std.setLayout(panel_stdLayout);
        panel_stdLayout.setHorizontalGroup(
            panel_stdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(panel_stdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_stdLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl_std)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_stdLayout.setVerticalGroup(
            panel_stdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(panel_stdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_stdLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl_std)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_mark.setBackground(new java.awt.Color(0, 102, 102));

        lbl_marksheet.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_marksheet.setForeground(new java.awt.Color(255, 255, 255));
        lbl_marksheet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view report.png"))); // NOI18N
        lbl_marksheet.setText("   Marksheet");
        lbl_marksheet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_marksheetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_marksheetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_marksheetMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_marksheetMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_markLayout = new javax.swing.GroupLayout(panel_mark);
        panel_mark.setLayout(panel_markLayout);
        panel_markLayout.setHorizontalGroup(
            panel_markLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_markLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_marksheet, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        panel_markLayout.setVerticalGroup(
            panel_markLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_markLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbl_marksheet)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panel_course.setBackground(new java.awt.Color(0, 102, 102));

        lbl_course.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_course.setForeground(new java.awt.Color(255, 255, 255));
        lbl_course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/text-book-opened-from-top-view.png"))); // NOI18N
        lbl_course.setText("   Courses");
        lbl_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_courseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_courseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_courseMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_courseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_courseLayout = new javax.swing.GroupLayout(panel_course);
        panel_course.setLayout(panel_courseLayout);
        panel_courseLayout.setHorizontalGroup(
            panel_courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_courseLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_course, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        panel_courseLayout.setVerticalGroup(
            panel_courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_courseLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbl_course, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panel_teacher.setBackground(new java.awt.Color(0, 102, 102));

        lbl_teacher.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_teacher.setForeground(new java.awt.Color(255, 255, 255));
        lbl_teacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/text-book-opened-from-top-view.png"))); // NOI18N
        lbl_teacher.setText("   Courses");
        lbl_teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_teacherMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_teacherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_teacherMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_teacherMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_teacherLayout = new javax.swing.GroupLayout(panel_teacher);
        panel_teacher.setLayout(panel_teacherLayout);
        panel_teacherLayout.setHorizontalGroup(
            panel_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_teacherLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbl_teacher, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_teacherLayout.setVerticalGroup(
            panel_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_teacherLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbl_teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_fees.setBackground(new java.awt.Color(0, 102, 102));

        lbl_fee.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_fee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        lbl_fee.setText("   Add Fees");
        lbl_fee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_feeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_feeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_feeMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_feeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_feesLayout = new javax.swing.GroupLayout(panel_fees);
        panel_fees.setLayout(panel_feesLayout);
        panel_feesLayout.setHorizontalGroup(
            panel_feesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_feesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_fee, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        panel_feesLayout.setVerticalGroup(
            panel_feesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_feesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbl_fee)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panel_score.setBackground(new java.awt.Color(0, 102, 102));

        lbl_score.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_score.setForeground(new java.awt.Color(255, 255, 255));
        lbl_score.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/text-book-opened-from-top-view.png"))); // NOI18N
        lbl_score.setText("   Courses");
        lbl_score.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_scoreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_scoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_scoreMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_scoreMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_scoreLayout = new javax.swing.GroupLayout(panel_score);
        panel_score.setLayout(panel_scoreLayout);
        panel_scoreLayout.setHorizontalGroup(
            panel_scoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_scoreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_score, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        panel_scoreLayout.setVerticalGroup(
            panel_scoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_scoreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_score, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_std, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_fees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_teacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_std, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_teacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_mark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_fees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1200, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_stdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_stdMouseEntered
        Color c1 = new Color(0,51,51);
        panel_std.setBackground(c1);
    }//GEN-LAST:event_lbl_stdMouseEntered

    private void lbl_stdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_stdMouseExited
        Color c1 = new Color(0,102, 102);
        panel_std.setBackground(c1);
    }//GEN-LAST:event_lbl_stdMouseExited

    private void lbl_teacherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_teacherMouseEntered
        Color c1 = new Color(0,51,51);
        panel_teacher.setBackground(c1);
    }//GEN-LAST:event_lbl_teacherMouseEntered

    private void lbl_teacherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_teacherMouseExited
        Color c1 = new Color(0,102, 102);
        panel_teacher.setBackground(c1);
    }//GEN-LAST:event_lbl_teacherMouseExited

    private void lbl_courseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_courseMouseEntered
        Color c1 = new Color(0,51,51);
        panel_course.setBackground(c1);
    }//GEN-LAST:event_lbl_courseMouseEntered

    private void lbl_courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_courseMouseExited
        Color c1 = new Color(0,102, 102);
        panel_course.setBackground(c1);
    }//GEN-LAST:event_lbl_courseMouseExited

    private void lbl_feeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_feeMouseEntered
        Color c1 = new Color(0,51,51);
        panel_fees.setBackground(c1);
    }//GEN-LAST:event_lbl_feeMouseEntered

    private void lbl_feeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_feeMouseExited
        Color c1 = new Color(0,102, 102);
        panel_fees.setBackground(c1);
    }//GEN-LAST:event_lbl_feeMouseExited

    private void lbl_scoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_scoreMouseEntered
       Color c1 = new Color(0,51,51);
       panel_score.setBackground(c1);
    }//GEN-LAST:event_lbl_scoreMouseEntered

    private void lbl_scoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_scoreMouseExited
        Color c1 = new Color(0,102, 102);
        panel_score.setBackground(c1);
    }//GEN-LAST:event_lbl_scoreMouseExited

    private void lbl_marksheetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_marksheetMouseEntered
        Color c1 = new Color(0,51,51);
        panel_mark.setBackground(c1);
    }//GEN-LAST:event_lbl_marksheetMouseEntered

    private void lbl_marksheetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_marksheetMouseExited
        Color c1 = new Color(0,102, 102);
        panel_mark.setBackground(c1);
    }//GEN-LAST:event_lbl_marksheetMouseExited

    private void lbl_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseEntered
        Color c1 = new Color(0,51,51);
        panel_logout.setBackground(c1);
    }//GEN-LAST:event_lbl_logoutMouseEntered

    private void lbl_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseExited
        Color c1 = new Color(0,102, 102);
        panel_logout.setBackground(c1);
    }//GEN-LAST:event_lbl_logoutMouseExited

    private void lbl_stdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_stdMouseClicked
       ManageStudent ms = new ManageStudent();
       ms.setTitle("Manage Student");
       ms.setLocationRelativeTo(null);
       ms.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbl_stdMouseClicked

     /*private String username;
      public void setUsername(String username) {
            this.username = username;
        lbl_username.setText("Welcome " + username);
    }*/
      
    private void lbl_teacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_teacherMouseClicked
        ManageFacultyForm mf = new ManageFacultyForm();
        mf.setTitle("Manage Faculty");
        mf.setLocationRelativeTo(null);
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_teacherMouseClicked

    private void lbl_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_courseMouseClicked
        ManageCourseForm mc = new ManageCourseForm();
        mc.setTitle("Manage Course");
        mc.setLocationRelativeTo(null);
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_courseMouseClicked

    private void lbl_feeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_feeMouseClicked
        ManageFeesForm mfe = new ManageFeesForm();
        mfe.setTitle("Manage Fees");
        mfe.setLocationRelativeTo(null);
        mfe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_feeMouseClicked

    private void lbl_scoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_scoreMouseClicked
        ManageScoreForm2 mfe = new ManageScoreForm2();
        mfe.setTitle("Manage Score");
        mfe.setLocationRelativeTo(null);
        mfe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_scoreMouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        int option = JOptionPane.showConfirmDialog(null, "<html><b style='font-size: 14px;color: #111810;'>Are you sure you want to logout?</b></html>", "Logout", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
               UserSession.setUsername(null);
               LoginForm lf = new LoginForm();
               lf.setTitle("LoginForm");
               lf.setLocationRelativeTo(null);
               lf.setVisible(true);
               this.dispose();
         }
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void lbl_marksheetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_marksheetMouseClicked
        MarkSheetForm ms = new MarkSheetForm();
        ms.setTitle("MarkSheet");
        ms.setLocationRelativeTo(null);
        ms.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_marksheetMouseClicked

    private void lbl_stdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_stdMouseReleased
       ManageStudent ms = new ManageStudent();
       ms.setTitle("Manage Student");
       ms.setLocationRelativeTo(null);
       ms.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lbl_stdMouseReleased

    private void lbl_teacherMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_teacherMouseReleased
        ManageFacultyForm mf = new ManageFacultyForm();
        mf.setTitle("Manage Faculty");
        mf.setLocationRelativeTo(null);
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_teacherMouseReleased

    private void lbl_courseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_courseMouseReleased
        ManageCourseForm mc = new ManageCourseForm();
        mc.setTitle("Manage Course");
        mc.setLocationRelativeTo(null);
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_courseMouseReleased

    private void lbl_feeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_feeMouseReleased
        ManageFeesForm mfe = new ManageFeesForm();
        mfe.setTitle("Manage Fees");
        mfe.setLocationRelativeTo(null);
        mfe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_feeMouseReleased

    private void lbl_scoreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_scoreMouseReleased
        ManageScoreForm2 mfe = new ManageScoreForm2();
        mfe.setTitle("Manage Score");
        mfe.setLocationRelativeTo(null);
        mfe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_scoreMouseReleased

    private void lbl_marksheetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_marksheetMouseReleased
        MarkSheetForm ms = new MarkSheetForm();
        ms.setTitle("MarkSheet");
        ms.setLocationRelativeTo(null);
        ms.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_marksheetMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home h = new Home();
                h.setTitle("Home");
                h.setLocationRelativeTo(null);
                h.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_course;
    private javax.swing.JLabel lbl_fee;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_marksheet;
    private javax.swing.JLabel lbl_score;
    private javax.swing.JLabel lbl_std;
    private javax.swing.JLabel lbl_teacher;
    public static javax.swing.JLabel lbl_username;
    public static javax.swing.JLabel lbl_username1;
    private javax.swing.JPanel panel_course;
    private javax.swing.JPanel panel_fees;
    private javax.swing.JPanel panel_logout;
    private javax.swing.JPanel panel_mark;
    private javax.swing.JPanel panel_score;
    private javax.swing.JPanel panel_std;
    private javax.swing.JPanel panel_teacher;
    // End of variables declaration//GEN-END:variables
}
