package Code;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Code.Course.*;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.*;

public class ManageCourseForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageCourseForm
     */
    Course c = new Course();

    public ManageCourseForm() {

        initComponents();

        c.fillStudentJTable(jTable1);

        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.BLUE);
        jTable1.setSelectionBackground(Color.BLACK);

         // Set custom table header font and size
        JTableHeader header = jTable1.getTableHeader();
        header.setFont(header.getFont().deriveFont(Font.BOLD, 16)); 
        
        // Center-align column headers
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer)jTable1.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        
        // Set header height
        header.setPreferredSize(new Dimension(header.getWidth(), 30)); 
        
        // Set border for the table
        Border border = BorderFactory.createLineBorder(Color.GRAY, 2);
        jTable1.setBorder(border);
        
         // Set border for the header
        header.setBorder(border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_course = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        cb_sem = new javax.swing.JComboBox<>();
        lbl_sem = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb_c1 = new javax.swing.JComboBox<>();
        cb_c4 = new javax.swing.JComboBox<>();
        cb_c3 = new javax.swing.JComboBox<>();
        cb_program = new javax.swing.JComboBox<>();
        cb_c2 = new javax.swing.JComboBox<>();
        panel_logout = new javax.swing.JPanel();
        lbl_logout1 = new javax.swing.JLabel();
        panel_back = new javax.swing.JPanel();
        lbl_back = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        lbl_course.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_course.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_course.setText("Manage Course");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Course 1 :");

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_remove.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_remove.setText("Delete");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Program", "Semester", "Course 1", "Course 2", "Course 3", "Course 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Program : ");

        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        cb_sem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", " " }));

        lbl_sem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_sem.setText("Semester :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Course 2 :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Course 4 :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Course 3 :");

        cb_c1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        cb_c4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        cb_c3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        cb_program.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Program", "BCA", "BBA" }));
        cb_program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_programActionPerformed(evt);
            }
        });

        cb_c2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        panel_logout.setBackground(new java.awt.Color(0, 102, 102));

        lbl_logout1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_logout1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        lbl_logout1.setText("   Logout");
        lbl_logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_logoutLayout = new javax.swing.GroupLayout(panel_logout);
        panel_logout.setLayout(panel_logoutLayout);
        panel_logoutLayout.setHorizontalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_logoutLayout.createSequentialGroup()
                    .addGap(0, 42, Short.MAX_VALUE)
                    .addComponent(lbl_logout1)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );
        panel_logoutLayout.setVerticalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_logoutLayout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(lbl_logout1)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        panel_back.setBackground(new java.awt.Color(0, 102, 102));

        lbl_back.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_back.setForeground(new java.awt.Color(255, 255, 255));
        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back-button.png"))); // NOI18N
        lbl_back.setText("   Back");
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_backLayout = new javax.swing.GroupLayout(panel_back);
        panel_back.setLayout(panel_backLayout);
        panel_backLayout.setHorizontalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
            .addGroup(panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backLayout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(lbl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        panel_backLayout.setVerticalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_back)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(lbl_course, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_sem)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_program, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_cancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_course, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_program, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sem))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cb_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cb_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(85, 85, 85))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        try {
            String program = cb_program.getSelectedItem().toString();
            int sem = Integer.parseInt(cb_sem.getSelectedItem().toString());
            String c1 = cb_c1.getSelectedItem().toString();
            String c2 = cb_c2.getSelectedItem().toString();
            String c3 = cb_c3.getSelectedItem().toString();
            String c4 = cb_c4.getSelectedItem().toString();

            if (!c.checkProgramSem('i', 0, program, sem, c1, c2, c3, c4)) {
                c.insertUpdateDeleteCourse('i', null, program, sem, c1, c2, c3, c4);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0); // Clear existing rows
                c.fillStudentJTable(jTable1);
                clearFields();
            } else {
                String errorMessage = "<html><b style='font-size: 12px;'>This Record Already Exist..<br> semester " + sem + " of " + program + "</b></html>";
                JOptionPane.showMessageDialog(null, errorMessage, "OK", JOptionPane.PLAIN_MESSAGE);
            }

        } catch (NullPointerException n) {
            String errorMessage = "<html><b style='font-size: 12px;'>Please Select Program..</b></html>";
            JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed

        if (jTable1.getSelectedRow() != -1) {
            int index = jTable1.getSelectedRow();
            int id = Integer.valueOf(jTable1.getValueAt(index, 0).toString());
            c.insertUpdateDeleteCourse('d', id, null, null, null, null, null, null);
            ManageCourseForm.jTable1.setModel(new DefaultTableModel(null, new Object[]{"Id", "Program", "Semester", "Course 1", "Course 2", "Course 3", "Course 4"}));
            c.fillStudentJTable(ManageCourseForm.jTable1);
            clearFields();
        } else {
            String errorMessage = "<html><b style='font-size: 12px;'>Please Select Field to delete..</b></html>";
            JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            try {
                int index = jTable1.getSelectedRow();
                int id = Integer.valueOf(jTable1.getValueAt(index, 0).toString());
                String program = cb_program.getSelectedItem().toString();
                int sem = Integer.parseInt(cb_sem.getSelectedItem().toString());

                String c1 = cb_c1.getSelectedItem().toString();
                String c2 = cb_c2.getSelectedItem().toString();
                String c3 = cb_c3.getSelectedItem().toString();
                String c4 = cb_c4.getSelectedItem().toString();

                if (!c.checkProgramSem('u', id, program, sem, c1, c2, c3, c4)) {
                    c.insertUpdateDeleteCourse('u', id, program, sem, c1, c2, c3, c4);
                    ManageCourseForm.jTable1.setModel(new DefaultTableModel(null, new Object[]{"Id", "Program", "Semester", "Course 1", "Course 2", "Course 3", "Course 4"}));
                    c.fillStudentJTable(ManageCourseForm.jTable1);

                    clearFields();
                } else {
                    String errorMessage = "<html><b style='font-size: 12px;'>Course Already Exist..</b></html>";
                    JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
                }

            } catch (NullPointerException n) {
                String errorMessage = "<html><b style='font-size: 12px;'>Please Select Field..</b></html>";
                JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            String errorMessage = "<html><b style='font-size: 12px;'>Please Select Field to edit..</b></html>";
            JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_editActionPerformed
    private void clearFields() {
        cb_program.setSelectedItem("Choose Program");
        cb_sem.setSelectedItem("1");

    }

    private int selectedRowIndex = -1;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();

        // Check if the row index is already selected
        if (index == selectedRowIndex) {
            // Deselect the row
            jTable1.getSelectionModel().clearSelection();
            // Clear form data
            clearFields();
            // Reset selectedRowIndex
            selectedRowIndex = -1;
        } else {
            cb_program.setSelectedItem(jTable1.getValueAt(index, 1).toString());
            String semValue = jTable1.getValueAt(index, 2).toString();
            for (int i = 0; i < cb_sem.getItemCount(); i++) {
                if (cb_sem.getItemAt(i).equals(semValue)) {
                    cb_sem.setSelectedIndex(i);
                    break;
                }
            }
            cb_c1.setSelectedItem(jTable1.getValueAt(index, 3).toString());
            cb_c2.setSelectedItem(jTable1.getValueAt(index, 4).toString());
            cb_c3.setSelectedItem(jTable1.getValueAt(index, 5).toString());
            cb_c4.setSelectedItem(jTable1.getValueAt(index, 6).toString());
            
            // Set selectedRowIndex
            selectedRowIndex = index;
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        int index = jTable1.getSelectedRow();
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            cb_program.setSelectedItem(jTable1.getValueAt(index, 1).toString());
            String semValue = jTable1.getValueAt(index, 2).toString();
            for (int i = 0; i < cb_sem.getItemCount(); i++) {
                if (cb_sem.getItemAt(i).equals(semValue)) {
                    cb_sem.setSelectedIndex(i);
                    break;
                }
            }
            cb_c1.setSelectedItem(jTable1.getValueAt(index, 3).toString());
            cb_c2.setSelectedItem(jTable1.getValueAt(index, 4).toString());
            cb_c3.setSelectedItem(jTable1.getValueAt(index, 5).toString());
            cb_c4.setSelectedItem(jTable1.getValueAt(index, 6).toString());
        }

    }//GEN-LAST:event_jTable1KeyReleased

    private void cb_programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_programActionPerformed

        String c1_bca[] = {"C Programming", "Web Programming", "C++ Programming", "OS", "Advance PHP", "ASP.NET"};
        String c2_bca[] = {"Creative English", "Communicative English", "Database management system", "System Design and Analysis", "C#.NET", "Networking"};
        String c3_bca[] = {"Computer Fundamentals", "Data structures", "Core PHP", "Core JAVA", "Advance Java", "Android"};
        String c4_bca[] = {"PC Software", "Web Technology", "Graphics and Animation", "Advance Python", "SEO", "Project"};

        String c1_bba[] = {"Financial Accounting", "Macroeconomics", "Quantitative techniques - I", "Environmental Management", "Banking & Insurance", "Human Behavior"};
        String c2_bba[] = {"Microeconomics", "Quantitative Techniques - II", "Essentials of IT", "Principles of Marketing", "Indian Economics", "Management Accounting"};
        String c3_bba[] = {"Principles of Management", "Effective Communications", "Business Analytics", "Direct Tax & Indirect Tax", "Financial Management", "Marketing Electives"};
        String c4_bba[] = {"India Socio-Political Economics", "Cost Accounting", "Human Resource Management", "Strategic Management", "Research Methodology", "Finance Electives"};

        cb_c1.removeAllItems();
        cb_c2.removeAllItems();
        cb_c3.removeAllItems();
        cb_c4.removeAllItems();

        if (cb_program.getSelectedItem() == "BCA") {

            for (String string : c1_bca) {
                cb_c1.addItem(string);
            }
            for (String string : c2_bca) {
                cb_c2.addItem(string);
            }
            for (String string : c3_bca) {
                cb_c3.addItem(string);
            }
            for (String string : c4_bca) {
                cb_c4.addItem(string);
            }

        }
        if (cb_program.getSelectedItem() == "BBA") {

            for (String string : c1_bba) {
                cb_c1.addItem(string);
            }
            for (String string : c2_bba) {
                cb_c2.addItem(string);
            }
            for (String string : c3_bba) {
                cb_c3.addItem(string);
            }
            for (String string : c4_bba) {
                cb_c4.addItem(string);
            }

        }

    }//GEN-LAST:event_cb_programActionPerformed

    private void lbl_logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseClicked
        int option = JOptionPane.showConfirmDialog(null, "<html><b style='font-size: 14px;color: #111810;'>Are you sure you want to logout?</b></html>", "Logout", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
               UserSession.setUsername(null);
               LoginForm lf = new LoginForm();
               lf.setTitle("LoginForm");
               lf.setLocationRelativeTo(null);
               lf.setVisible(true);
               this.dispose();
         }
    }//GEN-LAST:event_lbl_logout1MouseClicked

    private void lbl_logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseEntered
        Color c1 = new Color(0, 51, 51);
        panel_logout.setBackground(c1);
    }//GEN-LAST:event_lbl_logout1MouseEntered

    private void lbl_logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseExited
        Color c1 = new Color(0, 102, 102);
        panel_logout.setBackground(c1);
    }//GEN-LAST:event_lbl_logout1MouseExited

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        Home h = new Home();
        h.setTitle("Home");
        h.setVisible(true);
        h.pack();
        h.setLocationRelativeTo(null);
        h.lbl_username.setText("Welcome " + UserSession.getUsername());
        this.dispose();

    }//GEN-LAST:event_lbl_backMouseClicked

    private void lbl_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseEntered
        Color c1 = new Color(0, 51, 51);
        panel_back.setBackground(c1);
    }//GEN-LAST:event_lbl_backMouseEntered

    private void lbl_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseExited
        Color c1 = new Color(0, 102, 102);
        panel_back.setBackground(c1);
    }//GEN-LAST:event_lbl_backMouseExited

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearFields();
        jTable1.clearSelection();
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageCourseForm mc = new ManageCourseForm();
                //mc.setSize(1300,760);
                mc.setTitle("Manage Course");
                mc.setLocationRelativeTo(null);
                mc.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_remove;
    private javax.swing.JComboBox<String> cb_c1;
    private javax.swing.JComboBox<String> cb_c2;
    private javax.swing.JComboBox<String> cb_c3;
    private javax.swing.JComboBox<String> cb_c4;
    private javax.swing.JComboBox<String> cb_program;
    private javax.swing.JComboBox<String> cb_sem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_course;
    private javax.swing.JLabel lbl_logout1;
    private javax.swing.JLabel lbl_sem;
    private javax.swing.JPanel panel_back;
    private javax.swing.JPanel panel_logout;
    // End of variables declaration//GEN-END:variables
}
