/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;

import Code.MyConnection;
import Code.Score;
import static Code.ManageCourseForm.jTable1;
import java.sql.*;
import Code.Score.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.*;

/**
 *
 * @author DELL
 */
public class ManageScoreForm2 extends javax.swing.JFrame {

    /**
     * Creates new form ManageScoreForm2
     */
    Score s = new Score();

    public ManageScoreForm2() {
        initComponents();
        s.fillStudentJTable(jTable3);

        jTable3.setRowHeight(40);
        jTable3.setShowGrid(true);
        jTable3.setSelectionBackground(Color.BLACK);       
        jTable3.setGridColor(Color.BLUE);    
        
        // Set custom table header font and size
        JTableHeader header = jTable3.getTableHeader();
        header.setFont(header.getFont().deriveFont(Font.BOLD, 16)); 
        
        // Center-align column headers
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) jTable3.getTableHeader().getDefaultRenderer();    
        renderer.setHorizontalAlignment(JLabel.CENTER);
        
        // Set header height
        header.setPreferredSize(new Dimension(header.getWidth(), 30)); 
        
        // Set border for the table
        Border border = BorderFactory.createLineBorder(Color.GRAY, 2);
        jTable3.setBorder(border);
        
        // Set border for the header
        header.setBorder(border);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_course2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_enr = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        lbl_sem2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_enr2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_mc1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_mc2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_mc3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_mc4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btn_add2 = new javax.swing.JButton();
        btn_edit2 = new javax.swing.JButton();
        btn_remove2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        txt_c1 = new javax.swing.JTextField();
        txt_c2 = new javax.swing.JTextField();
        txt_c3 = new javax.swing.JTextField();
        txt_c4 = new javax.swing.JTextField();
        txt_program = new javax.swing.JTextField();
        txt_sem = new javax.swing.JTextField();
        panel_back = new javax.swing.JPanel();
        lbl_back = new javax.swing.JLabel();
        panel_logout = new javax.swing.JPanel();
        lbl_logout1 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        lbl_course2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_course2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_course2.setText("Manage Score");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Student Enrollement No:");

        txt_enr.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_search.setText("Search");
        btn_search.setNextFocusableComponent(txt_mc1);
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchbtn_searchActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("Program : ");

        lbl_sem2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_sem2.setText("Semester :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setText("Student enrollement:");

        txt_enr2.setEditable(false);
        txt_enr2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Course 1 :");

        txt_mc1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_mc1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mc1.setNextFocusableComponent(txt_mc2);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Course 2 :");

        txt_mc2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_mc2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mc2.setNextFocusableComponent(txt_mc3);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("Course 3 :");

        txt_mc3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_mc3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mc3.setNextFocusableComponent(txt_mc4);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel19.setText("Course 4 :");

        txt_mc4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_mc4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mc4.setNextFocusableComponent(btn_add2);
        txt_mc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mc4ActionPerformed(evt);
            }
        });

        jTable3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Program", "Semester", "Enrollment No", "Course 1 Marks", "Course 2 Marks", "Course 3 Marks", "Course 4 Marks"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3jTable1MouseClicked(evt);
            }
        });
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable3jTable1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        btn_add2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_add2.setText("Add");
        btn_add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add2btn_addActionPerformed(evt);
            }
        });

        btn_edit2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_edit2.setText("Edit");
        btn_edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit2btn_editActionPerformed(evt);
            }
        });

        btn_remove2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_remove2.setText("Delete");
        btn_remove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remove2btn_removeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Enter Marks ");

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearbtn_removeActionPerformed(evt);
            }
        });

        txt_c1.setEditable(false);
        txt_c1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_c2.setEditable(false);
        txt_c2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_c3.setEditable(false);
        txt_c3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_c4.setEditable(false);
        txt_c4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_program.setEditable(false);
        txt_program.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_sem.setEditable(false);
        txt_sem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        panel_back.setBackground(new java.awt.Color(0, 102, 102));

        lbl_back.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_back.setForeground(new java.awt.Color(255, 255, 255));
        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back-button.png"))); // NOI18N
        lbl_back.setText("   Back");
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_backLayout = new javax.swing.GroupLayout(panel_back);
        panel_back.setLayout(panel_backLayout);
        panel_backLayout.setHorizontalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
            .addGroup(panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backLayout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(lbl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        panel_backLayout.setVerticalGroup(
            panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(panel_backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_backLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_back)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        panel_logout.setBackground(new java.awt.Color(0, 102, 102));

        lbl_logout1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_logout1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        lbl_logout1.setText("   Logout");
        lbl_logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_logoutLayout = new javax.swing.GroupLayout(panel_logout);
        panel_logout.setLayout(panel_logoutLayout);
        panel_logoutLayout.setHorizontalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_logoutLayout.createSequentialGroup()
                    .addGap(0, 42, Short.MAX_VALUE)
                    .addComponent(lbl_logout1)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );
        panel_logoutLayout.setVerticalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_logoutLayout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(lbl_logout1)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(5, 5, 5)
                                .addComponent(txt_enr, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(457, 457, 457)
                                .addComponent(lbl_course2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(lbl_sem2)
                            .addComponent(jLabel22)
                            .addComponent(jLabel4)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_program, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_enr2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_mc2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_mc4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_mc3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_mc1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(148, 148, 148)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_add2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_edit2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_remove2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_course2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_enr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_program, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_enr2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_mc1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(lbl_sem2)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mc2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mc3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addComponent(txt_mc4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_remove2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_add2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchbtn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchbtn_searchActionPerformed
        // Check if the enrollment number field is empty
        if (txt_enr.getText().isEmpty()) {
            String message = "<html><b style='font-size: 12px;'>Please enter the enrollment number first!!!</b></html>";         
            JOptionPane.showMessageDialog(null, message , "Warning", JOptionPane.WARNING_MESSAGE);
            return; // Stop further execution
        }
        
        // Check if the enrollment number contains only digits
        String enrInput = txt_enr.getText().trim();
        if (!enrInput.matches("\\d+")) {
            String message = "<html><b style='font-size: 12px;'>Enrollment number should contain only digits!!!</b></html>";         
            JOptionPane.showMessageDialog(null, message , "Warning", JOptionPane.WARNING_MESSAGE);
            return; // Stop further execution
        }   
        
        int enr = Integer.valueOf(txt_enr.getText().toString());

        if (s.findId(enr)) {
            if(s.findCourse(s.sem, s.program)){
            try {
                int sem = s.sem;

                String program = s.program;

                s.getSubject();
                txt_c1.setText(s.c1);
                txt_c2.setText(s.c2);
                txt_c3.setText(s.c3);
                txt_c4.setText(s.c4);
                txt_program.setText(program);
                txt_sem.setText(sem + "");
                txt_enr2.setText(enr + "");
                

            } catch (Exception e) {
                String errorMessage = "<html><b style='font-size: 12px;'>" + e.getMessage() + "</b></html>";
                JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
        }
    }//GEN-LAST:event_btn_searchbtn_searchActionPerformed

    private void txt_mc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mc4ActionPerformed

    private int selectedRowIndex = -1;
    private void jTable3jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3jTable1MouseClicked
        int index = jTable3.getSelectedRow();
            if (index == selectedRowIndex) {
           // Deselect the row
           jTable3.getSelectionModel().clearSelection();
           // Clear form data
           clearFields();
           // Reset selectedRowIndex
           selectedRowIndex = -1;
       } else {
            String program = jTable3.getValueAt(index, 1).toString();
            int sem = Integer.parseInt(jTable3.getValueAt(index, 2).toString());
            txt_program.setText(program);
            txt_sem.setText(sem+"");
            int enr = Integer.parseInt(jTable3.getValueAt(index, 3).toString());

            txt_enr.setText(enr+"");
            int semValue = Integer.parseInt(jTable3.getValueAt(index, 2).toString());

            try {
                Connection con = MyConnection.getConnection();
                PreparedStatement pr = con.prepareStatement("select * from coursedetails where semester=? and program=?");
                pr.setInt(1, semValue);
                pr.setString(2, program);

                ResultSet rs = pr.executeQuery();
                if (rs.next()) {
                    txt_c1.setText(rs.getString("c1"));
                    txt_c2.setText(rs.getString("c2"));
                    txt_c3.setText(rs.getString("c3"));
                    txt_c4.setText(rs.getString("c4"));
                }
            } catch (Exception e) {
                String errorMessage = "<html><b style='font-size: 12px;'>" + e.getMessage() + "</b></html>";
                JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
            }
            txt_enr2.setText(jTable3.getValueAt(index, 3).toString());
            txt_mc1.setText(jTable3.getValueAt(index, 4).toString());
            txt_mc2.setText(jTable3.getValueAt(index, 5).toString());
            txt_mc3.setText(jTable3.getValueAt(index, 6).toString());
            txt_mc4.setText(jTable3.getValueAt(index, 7).toString());
            
            // Set selectedRowIndex
            selectedRowIndex = index;
        }

    }//GEN-LAST:event_jTable3jTable1MouseClicked

    private void jTable3jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3jTable1KeyReleased
        int index = jTable3.getSelectedRow();
        String program = jTable3.getValueAt(index, 1).toString();
        int sem = Integer.parseInt(jTable3.getValueAt(index, 2).toString());
        int enr = Integer.parseInt(jTable3.getValueAt(index, 3).toString());
        txt_program.setText(sem+"");
        txt_enr.setText(enr+"");
        txt_sem.setText(program);
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            
            int semValue = Integer.parseInt(jTable3.getValueAt(index, 2).toString());

            try {
                Connection con = MyConnection.getConnection();
                PreparedStatement pr = con.prepareStatement("select * from coursedetails where semester=? and program=?");
                pr.setInt(1, semValue);
                pr.setString(2, program);

                ResultSet rs = pr.executeQuery();
                if (rs.next()) {
                    txt_c1.setText(rs.getString("c1"));
                    txt_c2.setText(rs.getString("c2"));
                    txt_c3.setText(rs.getString("c3"));
                    txt_c4.setText(rs.getString("c4"));
                }
            } catch (Exception e) {
                String errorMessage = "<html><b style='font-size: 12px;'>" + e.getMessage() + "</b></html>";
                JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
            }
            txt_enr2.setText(jTable3.getValueAt(index, 3).toString());
            txt_mc1.setText(jTable3.getValueAt(index, 4).toString());
            txt_mc2.setText(jTable3.getValueAt(index, 5).toString());
            txt_mc3.setText(jTable3.getValueAt(index, 6).toString());
            txt_mc4.setText(jTable3.getValueAt(index, 7).toString());
            
        }
    }//GEN-LAST:event_jTable3jTable1KeyReleased
    
    private void btn_add2btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add2btn_addActionPerformed

        try {
            String program = txt_program.getText();
            int sem = Integer.parseInt(txt_sem.getText().toString());
            String enr = txt_enr2.getText();
            int toenr = Integer.parseInt(enr);
            int c1m = Integer.parseInt(txt_mc1.getText());
            int c2m = Integer.parseInt(txt_mc2.getText());
            int c3m = Integer.parseInt(txt_mc3.getText());
            int c4m = Integer.parseInt(txt_mc4.getText());
            
//            // Limiting the score to maximum 100
//            c1m = Math.min(c1m, 100);
//            c2m = Math.min(c2m, 100);
//            c3m = Math.min(c3m, 100);
//            c4m = Math.min(c4m, 100);
        
            // Check if any score is above 100
            if (c1m > 100 || c2m > 100 || c3m > 100 || c4m > 100) {
                String warningMessage = "<html><b style='font-size: 12px;'>Please ensure that the scores are between 0 and 100...</b></html>";
                JOptionPane.showMessageDialog(null, warningMessage, "Warning", JOptionPane.WARNING_MESSAGE);
            }
            else{
                if (!(program.equals("Choose Program") && enr.equals("") && c1m == 0 && c2m == 0 && c3m == 0 && c4m == 0)) {
                    if (s.findId(toenr)) {
                        if (enr.matches("\\d+")) {
                            if (!s.checkMarksSem('i', null, program, sem, toenr, c1m, c2m, c3m, c4m)) {
                                s.insertUpdateDeleteScore('i', null, program, sem, toenr, c1m, c2m, c3m, c4m);
                                DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
                                model.setRowCount(0); // Clear existing rows
                                s.fillStudentJTable(jTable3);
                                clearFields();
                            } else {
                                String errorMessage = "<html><b style='font-size: 12px;'>This Record Already Exist..<br> semester " + sem + " of " + program + "</b></html>";
                                JOptionPane.showMessageDialog(null, errorMessage, "OK", JOptionPane.PLAIN_MESSAGE);
                            }
                        } else {
                            String errorMessage = "<html><b style='font-size: 12px;'>String Value not allowed in marks...</b></html>";
                            JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
                        }
                    }

                } else {
                    String errorMessage = "<html><b style='font-size: 12px;'>Please Fill Empty Field....</b></html>";
                    JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
                }
            }
            } catch (Exception e) {
                String errorMessage = "<html><b style='font-size: 12px;'>Please provide valid value..</b></html>";
                JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
            }


    }//GEN-LAST:event_btn_add2btn_addActionPerformed
    public void clearFields() {
        txt_enr.setText("");
        txt_enr2.setText("");
        txt_program.setText("");
        txt_sem.setText("");
        txt_mc1.setText("");
        txt_mc2.setText("");
        txt_mc3.setText("");
        txt_mc4.setText("");
        txt_c1.setText("");
        txt_c2.setText("");
        txt_c3.setText("");
        txt_c4.setText("");
    }
    private void btn_edit2btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit2btn_editActionPerformed
        if (jTable3.getSelectedRow() != -1) {
            try {
                int index = jTable3.getSelectedRow();
                int id = Integer.valueOf(jTable3.getValueAt(index, 0).toString());
                String program = txt_program.getText();
                int enr = Integer.valueOf(txt_enr2.getText());
                int sem = Integer.valueOf(txt_sem.getText().toString());

                int c1 = Integer.valueOf(txt_mc1.getText().toString());
                int c2 = Integer.valueOf(txt_mc2.getText().toString());
                int c3 = Integer.valueOf(txt_mc3.getText().toString());
                int c4 = Integer.valueOf(txt_mc4.getText().toString());
                
                // Check if any score exceeds 100
                if (c1 > 100 || c2 > 100 || c3 > 100 || c4 > 100) {
                    String warningMessage = "<html><b style='font-size: 12px;'>Please ensure that the scores are between 0 and 100...</b></html>";
                    JOptionPane.showMessageDialog(null, warningMessage, "Warning", JOptionPane.WARNING_MESSAGE);
                } else {
                    if (s.findId(enr)) {
                        if (!s.checkMarksSem('u', id, program, sem, enr, c1, c2, c3, c4)) {
                            s.insertUpdateDeleteScore('u', id, program, sem, enr, c1, c2, c3, c4);
                            ManageScoreForm2.jTable3.setModel(new DefaultTableModel(null, new Object[]{"Id", "Program", "Semester", "Enrollment No", "Course 1 Marks", "Course 2 Marks", "Course 3 Marks", "Course 4 Marks"}));
                            s.fillStudentJTable(ManageScoreForm2.jTable3);

                            clearFields();
                        } else {
                            String errorMessage = "<html><b style='font-size: 12px;'>Score Already Given..</b></html>";
                            JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                }

                } catch (Exception n) {
                    String errorMessage = "<html><b style='font-size: 12px;'>" + n.getMessage() + "</b></html>";
                    JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                String errorMessage = "<html><b style='font-size: 12px;'>Please Select Field to edit..</b></html>";
                JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_edit2btn_editActionPerformed

    private void btn_remove2btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remove2btn_removeActionPerformed

        if (jTable3.getSelectedRow() != -1) {
            int index = jTable3.getSelectedRow();
            int id = Integer.valueOf(jTable3.getValueAt(index, 0).toString());
            s.insertUpdateDeleteScore('d', id, null, null, null, null, null, null, null);
            ManageScoreForm2.jTable3.setModel(new DefaultTableModel(null, new Object[]{"Id", "Program", "Semester", "Enrollment no", "Course 1 marks", "Course 2 marks", "Course 3 marks", "Course 4 marks"}));
            s.fillStudentJTable(ManageScoreForm2.jTable3);
            clearFields();
        } else {
            String errorMessage = "<html><b style='font-size: 12px;'>Please Select Field to delete..</b></html>";
            JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_remove2btn_removeActionPerformed

    private void btn_clearbtn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearbtn_removeActionPerformed
        txt_enr.setText("");
        txt_enr2.setText("");
        txt_program.setText("");
        txt_sem.setText("");
        txt_mc1.setText("");
        txt_mc2.setText("");
        txt_mc3.setText("");
        txt_mc4.setText("");
        txt_c1.setText("");
        txt_c2.setText("");
        txt_c3.setText("");
        txt_c4.setText("");
        jTable3.clearSelection();
    }//GEN-LAST:event_btn_clearbtn_removeActionPerformed

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        Home h = new Home();
        h.setTitle("Home");
        h.setVisible(true);
        h.pack();
        h.setLocationRelativeTo(null);
        h.lbl_username.setText("Welcome " + UserSession.getUsername());
        this.dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    private void lbl_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseEntered
        Color c1 = new Color(0,51,51);
        panel_back.setBackground(c1);
    }//GEN-LAST:event_lbl_backMouseEntered

    private void lbl_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseExited
        Color c1 = new Color(0,102, 102);
        panel_back.setBackground(c1);
    }//GEN-LAST:event_lbl_backMouseExited

    private void lbl_logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseClicked
       int option = JOptionPane.showConfirmDialog(null, "<html><b style='font-size: 14px;color: #111810;'>Are you sure you want to logout?</b></html>", "Logout", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
               UserSession.setUsername(null);
               LoginForm lf = new LoginForm();
               lf.setTitle("LoginForm");
               lf.setLocationRelativeTo(null);
               lf.setVisible(true);
               this.dispose();
         }
    }//GEN-LAST:event_lbl_logout1MouseClicked

    private void lbl_logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseEntered
        Color c1 = new Color(0,51,51);
        panel_logout.setBackground(c1);
    }//GEN-LAST:event_lbl_logout1MouseEntered

    private void lbl_logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseExited
        Color c1 = new Color(0,102, 102);
        panel_logout.setBackground(c1);
    }//GEN-LAST:event_lbl_logout1MouseExited

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageScoreForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageScoreForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageScoreForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageScoreForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageScoreForm2 mf = new ManageScoreForm2();
                mf.setTitle("Manage Score");
                mf.setLocationRelativeTo(null);
                mf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add2;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_edit2;
    private javax.swing.JButton btn_remove2;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable3;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_course2;
    private javax.swing.JLabel lbl_logout1;
    private javax.swing.JLabel lbl_sem2;
    private javax.swing.JPanel panel_back;
    private javax.swing.JPanel panel_logout;
    private javax.swing.JTextField txt_c1;
    private javax.swing.JTextField txt_c2;
    private javax.swing.JTextField txt_c3;
    private javax.swing.JTextField txt_c4;
    private javax.swing.JTextField txt_enr;
    private javax.swing.JTextField txt_enr2;
    private javax.swing.JTextField txt_mc1;
    private javax.swing.JTextField txt_mc2;
    private javax.swing.JTextField txt_mc3;
    private javax.swing.JTextField txt_mc4;
    private javax.swing.JTextField txt_program;
    private javax.swing.JTextField txt_sem;
    // End of variables declaration//GEN-END:variables
}
