/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;

import static Code.ManageCourseForm.jTable1;
import Code.Marksheet.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.*;
/**
 *
 * @author DELL
 */
public class MarkSheetForm extends javax.swing.JFrame {

    /**
     * Creates new form MarkSheetForm
     */
    Marksheet m = new Marksheet();

    public MarkSheetForm() {
        initComponents();

        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.BLUE);
        jTable1.setSelectionBackground(Color.BLACK);

        // Set custom table header font and size
        JTableHeader header = jTable1.getTableHeader();
        header.setFont(header.getFont().deriveFont(Font.BOLD, 16)); 
        
        // Center-align column headers
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer)jTable1.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
         
        // Set header height
        header.setPreferredSize(new Dimension(header.getWidth(), 30)); 

        // Set border for the table
        Border border = BorderFactory.createLineBorder(Color.GRAY, 2);
        jTable1.setBorder(border);
        
        // Set border for the header
        header.setBorder(border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_course = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_sname = new javax.swing.JTextField();
        txt_gender = new javax.swing.JTextField();
        txt_mob = new javax.swing.JTextField();
        txt_program = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_sem = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_enr = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_marks = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_grade = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        panel_logout = new javax.swing.JPanel();
        lbl_logout1 = new javax.swing.JLabel();
        panel_back2 = new javax.swing.JPanel();
        lbl_back2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        lbl_course.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_course.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_course.setText("Student Marksheet");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Student Name :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Mobile No :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Program :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Semester :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Gender :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Email :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Father Name :");

        txt_sname.setEditable(false);
        txt_sname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_gender.setEditable(false);
        txt_gender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_mob.setEditable(false);
        txt_mob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_program.setEditable(false);
        txt_program.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_email.setEditable(false);
        txt_email.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_sem.setEditable(false);
        txt_sem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_fname.setEditable(false);
        txt_fname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 51)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Total Marks", "Passing Marks", "Obtain Marks", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Enrollment No :");

        txt_enr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Total Marks :");

        txt_marks.setEditable(false);
        txt_marks.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Grade :");

        txt_grade.setEditable(false);
        txt_grade.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_print.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_print.setText("Download");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        panel_logout.setBackground(new java.awt.Color(0, 102, 102));

        lbl_logout1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_logout1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        lbl_logout1.setText("   Logout");
        lbl_logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_logoutLayout = new javax.swing.GroupLayout(panel_logout);
        panel_logout.setLayout(panel_logoutLayout);
        panel_logoutLayout.setHorizontalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_logoutLayout.createSequentialGroup()
                    .addGap(0, 42, Short.MAX_VALUE)
                    .addComponent(lbl_logout1)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );
        panel_logoutLayout.setVerticalGroup(
            panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(panel_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_logoutLayout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(lbl_logout1)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        panel_back2.setBackground(new java.awt.Color(0, 102, 102));

        lbl_back2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_back2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back-button.png"))); // NOI18N
        lbl_back2.setText("   Back");
        lbl_back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_back2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_back2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_back2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_back2Layout = new javax.swing.GroupLayout(panel_back2);
        panel_back2.setLayout(panel_back2Layout);
        panel_back2Layout.setHorizontalGroup(
            panel_back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
            .addGroup(panel_back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_back2Layout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(lbl_back2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        panel_back2Layout.setVerticalGroup(
            panel_back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(panel_back2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_back2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_back2)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_program, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_mob, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_enr, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_sname, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panel_back2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel11)
                .addGap(63, 63, 63)
                .addComponent(txt_marks, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281)
                .addComponent(jLabel12)
                .addGap(60, 60, 60)
                .addComponent(txt_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(lbl_course, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_course, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_enr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(panel_back2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(panel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mob, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_program, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_marks, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearfields()
    {
        txt_sname.setText("");
        txt_fname.setText("");
        txt_gender.setText("");
        txt_mob.setText("");
        txt_email.setText("");
        txt_email.setText("");
        txt_program.setText("");
        txt_sem.setText("");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        txt_grade.setText("");
        txt_marks.setText("");
    }
    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        clearfields();
        
        // Check if enrollment number field is empty
        if (txt_enr.getText().isEmpty()) {
            String message = "<html><b style='font-size: 12px;'>Please enter the enrollment number first!!!</b></html>";         
            JOptionPane.showMessageDialog(null, message , "Warning", JOptionPane.WARNING_MESSAGE);
            return; // Stop further execution
        }
        
         // Check if the enrollment number contains only digits
        String enrInput = txt_enr.getText().trim();
        if (!enrInput.matches("\\d+")) {
            String message = "<html><b style='font-size: 12px;'>Enrollment number should contain only digits!!!</b></html>";         
            JOptionPane.showMessageDialog(null, message , "Warning", JOptionPane.WARNING_MESSAGE);
            return; // Stop further execution
        }  
    
        int enr = Integer.parseInt(txt_enr.getText());
        if (m.findId(enr)) {

            txt_sname.setText(m.sname);
            txt_fname.setText(m.fname);
            txt_gender.setText(m.gender);
            txt_mob.setText(m.mobileno);
            txt_email.setText(m.email);
            txt_email.setText(m.email);
            txt_program.setText(m.program);
            txt_sem.setText(m.sem + "");

            if (m.findScoreId(enr)) {
                m.fillMarkSheetJTable(jTable1);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0); // Clear existing rows
                m.fillMarkSheetJTable(jTable1);

                txt_marks.setText(m.totalOfMarks + "");
                txt_grade.setText(m.fGrade + "");
                //char charGrade = m.getGrade(m.fGrade);
                //txt_grade.setText(charGrade + "");
                if (!m.findMarksheetId(enr)) {
                    try {
                        Connection con = MyConnection.getConnection();
                        PreparedStatement pr = con.prepareStatement("insert into marksheet(enrollmentno,total,grade) values(?,?,?)");
                        pr.setInt(1, enr);
                        pr.setInt(2, m.totalOfMarks);
                        pr.setString(3, String.valueOf(m.fGrade));

//                        int i = pr.executeUpdate();
//                        if (i == 1) {
//                            String message = "<html><b style='font-size: 12px;'>MarkSheet Generated..</b></html>";
//                            JOptionPane.showMessageDialog(null, message, "Success",  JOptionPane.INFORMATION_MESSAGE);
//                        }

                        int rowsInserted = pr.executeUpdate();
                        if (rowsInserted > 0) {
                            String message = "<html><b style='font-size: 12px;'>Marksheet Generated..</b></html>";
                            JOptionPane.showMessageDialog(null, message, "Success", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            String message = "<html><b style='font-size: 12px;'>Failed to generate marksheet..</b></html>";
                            JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.WARNING_MESSAGE);
                        }
                    } catch (SQLException e) {
                        String errorMessage = "<html><b style='font-size: 12px;'>" + e.getMessage() + "</b></html>";
                        JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    //String message = "<html><b style='font-size: 12px;'>MarkSheet Generated..</b></html>";
                    //JOptionPane.showMessageDialog(null, message, "Success",  JOptionPane.INFORMATION_MESSAGE);
                      
                    int newTotal = m.totalOfMarks; // Store the current total marks
                    char newGrade = m.fGrade; // Store the current grade
                     // Update existing marksheet
                    try {
                        Connection con = MyConnection.getConnection();
                        PreparedStatement pr = con.prepareStatement("UPDATE marksheet SET total=?, grade=? WHERE enrollmentno=?");
                        pr.setInt(1, newTotal);
                        pr.setString(2, String.valueOf(newGrade));
                        pr.setInt(3, enr);

                        int rowsUpdated = pr.executeUpdate();
                        if (rowsUpdated > 0) {
                            String message = "<html><b style='font-size: 12px;'>Marksheet Generated!!!</b></html>";
                            JOptionPane.showMessageDialog(null, message, "Success", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            String message = "<html><b style='font-size: 12px;'>Failed to update marksheet..</b></html>";
                            JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.WARNING_MESSAGE);
                        }
                    } catch (SQLException e) {
                        String errorMessage = "<html><b style='font-size: 12px;'>" + e.getMessage() + "</b></html>";
                        JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.WARNING_MESSAGE);
                    }
                }

            }

        }

    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_enr.setText("");
        txt_sname.setText("");
        txt_fname.setText("");
        txt_gender.setText("");
        txt_mob.setText("");
        txt_email.setText("");
        txt_email.setText("");
        txt_program.setText("");
        txt_sem.setText("");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        txt_grade.setText("");
        txt_marks.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        
        /*MessageFormat header = new MessageFormat("Marksheet");
        MessageFormat footer = new MessageFormat("Thank You");

        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException p) {
            String errorMessage = "<html><b style='font-size: 12px;'>" + p.getMessage() + "</b></html>";
            JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
        }*/
        
        // Check if enrollment number field is empty
        if (txt_enr.getText().isEmpty()) {
            String message = "<html><b style='font-size: 12px;'>Please enter the enrollment number first!!!</b></html>";         
            JOptionPane.showMessageDialog(null, message , "Warning", JOptionPane.WARNING_MESSAGE);
            return; // Stop further execution
        }

        int enr = Integer.parseInt(txt_enr.getText());
        if (m.findId(enr)) {
             // Assuming you have a jTable1 representing mark sheet details
            if (jTable1.getRowCount() == 0) {
                String message = "<html><b style='font-size: 12px;'>Please enter student scores first!!!</b></html>";         
                JOptionPane.showMessageDialog(null, message , "Warning", JOptionPane.WARNING_MESSAGE);
                return; // Stop further execution
            }
            String sname = m.sname;
            String fname = m.fname;
            String gender = m.gender;
            String mobileno = m.mobileno;
            String email = m.email;
            String program = m.program;
            int sem = m.sem;
            int totalMarks = m.totalOfMarks;
            char finalGrade = m.fGrade;

            // Assuming you have a jTable1 representing mark sheet details
            MarksheetPDF marksheetPDF = new MarksheetPDF();
            marksheetPDF.generatePDFMarksheet(enr,sname, fname, gender, mobileno, email, program, sem, totalMarks, finalGrade, jTable1);
        }
    
    }//GEN-LAST:event_btn_printActionPerformed

    private void lbl_back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseClicked
        Home h = new Home();
        h.setTitle("Home");
        h.setVisible(true);
        h.pack();
        h.setLocationRelativeTo(null);
        h.lbl_username.setText("Welcome " + UserSession.getUsername());
        this.dispose();
    }//GEN-LAST:event_lbl_back2MouseClicked

    private void lbl_back2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseEntered
        Color c1 = new Color(0,51,51);
        panel_back2.setBackground(c1);
    }//GEN-LAST:event_lbl_back2MouseEntered

    private void lbl_back2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseExited
        Color c1 = new Color(0,102, 102);
        panel_back2.setBackground(c1);
    }//GEN-LAST:event_lbl_back2MouseExited

    private void lbl_logout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseClicked
       int option = JOptionPane.showConfirmDialog(null, "<html><b style='font-size: 14px;color: #111810;'>Are you sure you want to logout?</b></html>", "Logout", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
               UserSession.setUsername(null);
               LoginForm lf = new LoginForm();
               lf.setTitle("LoginForm");
               lf.setLocationRelativeTo(null);
               lf.setVisible(true);
               this.dispose();
         }
    }//GEN-LAST:event_lbl_logout1MouseClicked

    private void lbl_logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseEntered
        Color c1 = new Color(0,51,51);
        panel_logout.setBackground(c1);
    }//GEN-LAST:event_lbl_logout1MouseEntered

    private void lbl_logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseExited
        Color c1 = new Color(0,102, 102);
        panel_logout.setBackground(c1);
    }//GEN-LAST:event_lbl_logout1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarkSheetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarkSheetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarkSheetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarkSheetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MarkSheetForm mf = new MarkSheetForm();
                mf.setTitle("MarkSheet");
                mf.setLocationRelativeTo(null);
                mf.setVisible(true);
                //mf.setExtendedState(JFrame.MAXIMIZED_BOTH); 
                 //mf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_back2;
    private javax.swing.JLabel lbl_course;
    private javax.swing.JLabel lbl_logout1;
    private javax.swing.JPanel panel_back2;
    private javax.swing.JPanel panel_logout;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_enr;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_grade;
    private javax.swing.JTextField txt_marks;
    private javax.swing.JTextField txt_mob;
    private javax.swing.JTextField txt_program;
    private javax.swing.JTextField txt_sem;
    private javax.swing.JTextField txt_sname;
    // End of variables declaration//GEN-END:variables
}
